apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: test.ck8s.crossplane.io
spec:
  defaultCompositionRef:
    name: ck8s
  group: ck8s.crossplane.io
  names:
    categories:
      - crossplane
      - ck8s
    kind: test
    plural: test
  versions:
    - additionalPrinterColumns: []
      name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                parameters:
                  type: object
                  description: configuration parameters.
                  properties:
                    vpcId:
                      type: string
                      description: VPCID is the ID of the VPC.
                    location:
                      type: string
                      description: Location is the region you'd like stuff is created in
                    version:
                      type: string
                      description: The desired Kubernetes version for your cluster.
                    min:
                      type: integer
                      description: The current number of worker nodes that the managed node group should maintain
                    max:
                      type: integer
                      description: The maximum number of worker nodes that the managed node group can scale out to
                  required:
                  - vpcId
                  - location
                  - version
                  - min
                  - max
              required:
              - parameters
            status:
              description: A Status represents the observed state
              properties:
                eks:
                  description: Freeform field containing status information for eks
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
              type: object
